apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myreplicaset
  labels:
    app: myapp
    tier: frontend
spec:
  
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      
  containers:
  - name: mynode
    image: armaansidhus224126633/6.1p
    ports:
    - containerPort: 8080



